### ISSUE TITLE
Fix styling on raw steno keys in hints on finished lesson screen

### ISSUE THREAD

**Issue by didoesdigital** [didoesdigital/typey-type#13]
# Problem

The styling on individual raw steno keys in hints on finished lesson screen has a background color that does not match the background color for full steno strokes:
![image](https://user-images.githubusercontent.com/2476974/71979142-14ce9e80-3271-11ea-9606-909a305b3269.png)

In this example, the outside edges around `WAS` are a different color to the background behind the letters `WAS`. They should be the same color.

## Details

The `steno-stroke` class is used in all of the following places:

![image](https://user-images.githubusercontent.com/2476974/71979407-bbb33a80-3271-11ea-8dee-66c688ced972.png)
<https://didoesdigital.com/typey-type/lessons/fundamentals/one-syllable-words-with-compound-clusters/overview>

![image](https://user-images.githubusercontent.com/2476974/71979434-d38abe80-3271-11ea-807e-1d703823b4a9.png)
<https://didoesdigital.com/typey-type/lessons/fundamentals/introduction/>

![image](https://user-images.githubusercontent.com/2476974/71979464-e7cebb80-3271-11ea-8bb8-136fcb5a10f3.png)
<https://didoesdigital.com/typey-type/lessons>

![image](https://user-images.githubusercontent.com/2476974/71979562-1cdb0e00-3272-11ea-92f9-79b0a2970ba9.png)
<https://didoesdigital.com/typey-type/dictionaries>
<https://didoesdigital.com/typey-type/lookup>
<https://didoesdigital.com/typey-type/lessons/fundamentals/introduction/flashcards>

# Approach

We no longer need individual styling for individual raw steno keys anywhere so we can remove the classes for `raw-steno-key raw-steno-key--subtle` on the finished screen or in CSS.

1. Remove classes in CSS.
2. Remove classes in finished screen JSX.
3. Take screenshots of all the places steno strokes are used and check they look good.

**Comment by didoesdigital** [comment]
Good clarification, @MohitBansal321 ! 

In the CSS, we need to remove `raw-steno-key` and `raw-steno-key--subtle` and keep `steno-stroke` and `steno-stroke--subtle`. 

In the JSX, we need to replace references to `raw-steno-key` and `raw-steno-key--subtle` with `steno-stroke` and `steno-stroke--subtle`.

**Comment by MohitBansal321** [comment]
I am getting an error when I launch the development server
git clone URL
git submodule update --init --recursive
cd typey-type
yarn install
yarn start
This is how I install and run
@didoesdigital 
![image](https://github.com/didoesdigital/typey-type/assets/78220157/14061e25-b0f3-44f4-bd48-0fe9443072cf)

**Comment by didoesdigital** [comment]
Thanks for the detailed steps to reproduce. My best guess is that `git submodule update --init --recursive` was run outside the `typey-type` directory so it didn't actually update the submodules, so it's missing the necessary files like `misstrokes.json`. To fix this, try:

```
cd typey-type
git submodule update --init --recursive
yarn start
```

I'll update the README to be a bit clearer about the submodule update step

**Comment by didoesdigital** [comment]
Updated the README in https://github.com/didoesdigital/typey-type/commit/68f9bc9944f66f3df5dcce4a6fa6df5c9c8a1870

**Comment by MohitBansal321** [comment]
> Thanks for the detailed steps to reproduce. My best guess is that `git submodule update --init --recursive` was run outside the `typey-type` directory so it didn't actually update the submodules, so it's missing the necessary files like `misstrokes.json`. To fix this, try:
> 
> ```
> cd typey-type
> git submodule update --init --recursive
> yarn start
> ```
> 
> I'll update the README to be a bit clearer about the submodule update step

I already did this but i will do it again same error occur

**Comment by didoesdigital** [comment]
> I already did this but i will do it again same error occur 

If there continues to be errors, it would be useful to know:

- if there are any other errors shown before the errors in your previous screenshot
- what the console shows when you run the submodule update command
- what editor you're using and on what operating system (windows/mac/something else)

**Comment by MohitBansal321** [comment]
> > I already did this but i will do it again same error occur
> 
> If there continues to be errors, it would be useful to know:
> 
> * if there are any other errors shown before the errors in your previous screenshot
> * what the console shows when you run the submodule update command
> * what editor you're using and on what operating system (windows/mac/something else)

Some error before in my previous screenshot
![image](https://github.com/didoesdigital/typey-type/assets/78220157/5e8687de-c924-4635-9e0f-8864babf8f32)
![image](https://github.com/didoesdigital/typey-type/assets/78220157/46642e4f-e941-4b28-92a4-cf4b3b521dbb)
There are more
when I do submodule update command
![image](https://github.com/didoesdigital/typey-type/assets/78220157/99e576c7-d55a-4dbf-919a-6f8bb4062e9b)

I am using vs code editor and Windows 10 operating system

**Comment by didoesdigital** [comment]
Ok, with the additional errors around "error:0308010C:digital envelope routines::unsupported" I was able to work out there was an issue with Node v18+ where Typey Type had previously been built using Node v16. In order for Typey Type to work with Node 18 without errors, I updated a dependency in https://github.com/didoesdigital/typey-type/pull/136

@MohitBansal321 now try this:

- `git pull` on `master` to get the latest version of Typey Type with the fix for Node 18
- `yarn install` to install the updated package dependencies
- `yarn start`

**Comment by didoesdigital** [comment]
I've also just upgraded Typey Type to yarn v4 too: https://github.com/didoesdigital/typey-type/pull/137

**Comment by MohitBansal321** [comment]
I done all the changes but error still there 
![image](https://github.com/didoesdigital/typey-type/assets/78220157/518412ad-f5c6-4134-89b1-18b9e01e9026)
![image](https://github.com/didoesdigital/typey-type/assets/78220157/5a922196-99db-47f4-a326-9178f4df320d)
@didoesdigital

**Comment by didoesdigital** [comment]
@MohitBansal321 thanks for persevering! I've done some digging, and it seems like on Windows there are some extra steps needed to turn on symlinks/git symlinks.

Option A) try to work out symlinks on Windows. I don't know much about that. I think there's some Developer Mode that needs to be turned on and then a git configuration run like `git config --global core.symlinks true`, and then switch branch to something else like `git checkout -b boop-symlinks` and back again `git checkout master` so it notices the git symlinks correctly. I'm afraid I can't be much help here. 

Option B) temporarily replace the symlinks with regular files locally on your machine without committing those changes. To do that, you'd copy 1. `typey-type-data/dictionaries/didoesdigital/misstrokes.json` to replace `src/json/misstrokes.json`, 2. copy `typey-type-data/lessons/` to replace `public/lessons/`, and 3. copy `typey-type-data/dictionaries/` to replace `public/dictionaries/`. Then `yarn start` should hopefully work. You'd need to be careful not to commit those changes.

I will also try think about other ways to make this easier 🤔

**Comment by MohitBansal321** [comment]
Its working thank you with this only copy the misstrokes from typey-type-data to replace src misstrokes 
@didoesdigital
