### ISSUE TITLE
[Suggestion] Remember settings for each lesson mode

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/typey-type#131]
Hi, I'll want to save lesson settings for each lesson, so I can start typing right away.

It's annoying to have to change settings if other settings are preferred

My current revision settings:
- 60 words
- 1 repetition

**Comment by didoesdigital** [comment]
That's a great idea. Thanks for sharing and mentioning the specific lesson settings you use.

**Comment by Monniasza** [comment]
do you work on it now?
`TKO U WORBG OPB T TPHOU STPH`

**Comment by didoesdigital** [comment]
@Monniasza I enjoyed your raw steno comment.

I've added a new feature in https://github.com/didoesdigital/typey-type/pull/132 to help address your scenario! I hope it works well for you!

**Comment by Monniasza** [comment]
I use a web app version. How do I update it?

**Comment by didoesdigital** [comment]
> I use a web app version. How do I update it?

Umm a hard refresh might do it? Might depend on your OS and browser, what are you using?

**Comment by Monniasza** [comment]
I'm using Brave Browser

**Comment by didoesdigital** [comment]
Oh, I don't know about that. I would guess Ctrl+Shift+R on Windows or Cmd+Shift+R on a mac?

**Comment by Monniasza** [comment]
The keyboard shortcut has applied changes. Thank you for the tip.
