### ISSUE TITLE
[BUG] Revise mode settings are not applied automatically

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/typey-type#134]
Last time, when I have suggested adding saving settings, the settings are applied to the discover mode, but they are not applied automatically to the revise mode.
To reproduce, just open the "My revision words" lesson

**Comment by didoesdigital** [comment]
Thanks @Monniasza for mentioning that saved study settings applied to the "my revision words" lesson would be useful to you. I've updated the progress revision lessons to respect the student's personal study presets. That's all of these:

<img width="1026" alt="image" src="https://github.com/didoesdigital/typey-type/assets/2476974/d3339669-754f-4f4e-a7a7-e47f6ba83887">
