### ISSUE TITLE
Hints don't reset when restarting lesson

### ISSUE THREAD

**Issue by Scoder12** [didoesdigital/typey-type#155]
1. Start a lesson in a mode that doesn't show hints by default, like "Practice"
2. Misstroke a word. Hint should pop up
3. Restart the lesson
Expected behavior: hint should disappear
Actual behavior: hint remains (every if it is a completely different word like in random sort mode)

**Comment by Scoder12** [comment]
My understanding of the codebase is limited, but from my debugging using React developer tools, it seems that `showStrokesInLesson` is the variable that isn't getting cleared.

**Comment by didoesdigital** [comment]
Thanks for raising the issue and including clear steps for reproducing the issue as well as hints at the possible cause 👏
