### ISSUE TITLE
Michela svg stretches screen on mobile

### ISSUE THREAD

**Issue by Zireael07** [didoesdigital/typey-type#161]
All the others do fit on screen but Michela doesn't.

**Comment by didoesdigital** [comment]
@Zireael07, thanks for flagging this issue! I have updated the diagram so it fits now:

<img width="818" alt="Italian Michela steno diagram on Writer page in responsive design view showing it fits on a 375px wide screen" src="https://github.com/didoesdigital/typey-type/assets/2476974/93a5461f-faf7-45d2-9795-e2e13c20ba73">

Once you've hard refreshed the [Writer page](https://didoesdigital.com/typey-type/writer), you should be able to see the changes.
