### ISSUE TITLE
diagramID-0-WAS SVG too small

### ISSUE THREAD

**Issue by Geremia** [didoesdigital/typey-type#24]
Please make the diagramID-0-WAS SVG image bigger or resizable. 140px is too small.

**Comment by didoesdigital** [comment]
@Geremia Can you tell me more? Do you mean the diagrams shown as hints in every lesson are too small? 140px is too small for what?

One option might be to use the zoom setting in your browser, which will increase the size of the image.

**Comment by Geremia** [comment]
@didoesdigital 140px is too small on a high-DPI monitor (mine is 196 dpi).
The ability to resize the <div> would be good.

**Comment by didoesdigital** [comment]
Thanks @Geremia , the context about the high-DPI monitor is useful. Can you possibly share a screenshot?

What would you gain by resizing?

**Comment by Geremia** [comment]
@didoesdigital Here's how it appears for me in Firefox 73.0b2:
![screenshot](https://i.stack.imgur.com/GHTME.png)

**Comment by didoesdigital** [comment]
Thanks @Geremia . That looks ok to me. Are you having difficulty reading the diagram?

**Comment by Geremia** [comment]
@Geremia I can read it, but resizablility would be nice.

**Comment by didoesdigital** [comment]
There's now a setting to change the diagram size:

<img width="1920" alt="Typey Type diagram size setting at 2.0" src="https://user-images.githubusercontent.com/2476974/152633039-c88b30bd-c56d-4454-81b0-21b3d6992032.png">
