### ISSUE TITLE
Statistics calculation issue

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/typey-type#27]
I finally got to a point where I have exhausted all the outlines Typey Type has available. The screen displayed "100% completion" before I had completed the final "Top 10000 Project Gutenberg words" exercise, but when I did, my final stats were that I had successfully typed 10347 words, and completed 100% of 10,000 words:

<img width="517" alt="Typey_Type___Progress" src="https://user-images.githubusercontent.com/543366/83206177-a6449b80-a193-11ea-81ed-96d2bf7248fd.png">

The Lessons Progress stats displayed as follows:

<img width="155" alt="Typey_Type___Progress" src="https://user-images.githubusercontent.com/543366/83206295-ead03700-a193-11ea-89c3-a047265c601c.png">

The text is a bit small, so I'll enumerate here the lessons in which the stats would lead me to believe there are still words left to stroke, but upon clicking through to them, I would be greeted with a "There are no words to write" screen:

- Multi-syllable words with prefixes · 911 of 927
- Multi-syllable words with suffixes · 1362 of 1380
- Multi-syllable words with doubled consonant letters · 1186 of 1201
- Multi-syllable words with multiple strokes · 3372 of 3431
- Fingerspelling · 26 of 52
- Punctuation · 29 of 30
- Top 1000 words · 998 of 1000
- Top 10000 Project Gutenberg words · 9928 of 10000

For analysis purposes, here is [my Typey Type progress JSON file](https://gist.github.com/paulfioravanti/8703573acb107e362ba32d527110550e) which gets me the output.

As an aside to this issue, Typey Type is _amazing software_, and I'm thrilled to be able to have gotten to "completion" 😄

**Comment by didoesdigital** [comment]
This is probably fixed in 8c93178 just like https://github.com/didoesdigital/typey-type/issues/20

Congrats again on finishing!

**Comment by paulfioravanti** [comment]
Hey @didoesdigital, I've just put up a [new gist of my progress file](https://gist.github.com/paulfioravanti/6e2b3209bf215ef585bc39e5c56afef7) as of 07 March 2021 (not sure what happened to the original one linked...).

After loading it into Typey Type, I can see that there are still issues around the counting, though the lessons where there are inconsistencies are slightly different than outlined in the original issue. Perhaps there's something amiss with my progress file...?

**Comment by didoesdigital** [comment]
Hmmm… Thanks for updating the gist for testing.

I've found at least one source of trouble: the "Simple typography" setting will change a back tick to into a single quote, decide that you haven't typed it because it's not in your met words for the purposes of calculating "progress", then decide you've already seen it for the purposes of showing "new words" in the lesson.

I've review all the code for presenting material and align the progress calculation to match. Thanks!

**Comment by didoesdigital** [comment]
Woohoo! 🎉

Thanks for testing the fix @paulfioravanti and confirming the improvement! 👏 It is now merged.
