### ISSUE TITLE
Remove search?

### ISSUE THREAD

**Issue by didoesdigital** [didoesdigital/typey-type#29]
# Overview

Should we remove lesson search from Typey Type? It seems like search is under-utilised and will take effort to update. I'd prefer to remove it (at least for now and maybe one day restore it, on the lessons index page, if I can make it better.) It also takes up valuable screen real estate in the navigation bar.

# Background

## Current use

Analytics (for people that don't block analytics) shows only 5 **Select** events where someone selected a lesson from the autocomplete dropdown:

- /collections/tech/react/lesson.txt * 2
- /collections/human-resources/hris-vocabulary/lesson.txt
- /stories/charles-perrault/the-ridiculous-wishes/lesson.txt
- /stories/hans-christian-andersen/in-the-nursery/lesson.txt

… and only 4 **Start** events where someone then started that lesson:

- /collections/tech/react/lesson.txt * 2
- /stories/charles-perrault/the-ridiculous-wishes/lesson.txt
- /stories/hans-christian-andersen/in-the-nursery/lesson.txt

I suspect the React and HRIS lesson events were from me, leaving only 2 successful uses of search in 3 months.

There were 689 **Change** events where a key stroke changed in the search query. Most search queries did not match any lessons. Here is a sample of the main searches that looked like words:

- misunderstanding
- i love
- keep it up
- hello
- magn
- commands
- consist
- happ
- hello, my name is […] (I've snipped the actual name listed)
- throug
- TPHOELG
- again
- arranged
- calf
- command
- divide
- faq
- form
- happy
- just briefs
- muscle
- Package
- particular
- preparing
- priority
- pristine
- prohibit
- transcript
- type of stenography
- unusual
- whose
- your

Some look like site searches for info, not lesson searches. For example, "type of stenography" "faq", and "form".

Some look like possible lesson searches that don't have good results (that could make for interesting lessons) such as "magn" (which I guess is magnum steno), "just briefs", "transcript", and "command".

Some look like spam. 

I cannot find search queries that match the 2 successful lesson selections, so it's possible the visitor in that case typed something like a space or one letter, and scrolled the whole list and picked something at random.

## Current problems

The current lesson search uses [react-autocomplete](https://github.com/reactjs/react-autocomplete), which appears to be deprecated. It seems like it should be replaced by [react-autosuggest](http://react-autosuggest.js.org/). 

React-autocomplete uses the deprecated [componentWillReceiveProps](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops), causing warnings in https://github.com/didoesdigital/typey-type/issues/7. 

Replacing react-autocomplete with react-suggest may slow down the process to upgrade React to use its latest features.

### Accessibility and usability

It was hard to build it so that it would be possible for screen reader users to skip over the long list of results and continue navigating the page. My dodgy work around was to show no results until you type your first character so screen reader users could at least tab through it without getting stuck in a long list if they didn't want to search. This means there are limited hints about what is actually available that you can search for, which may lead to people searching for site content like FAQ instead of lesson or collection names. 

It was also hard to separate focus (navigating through the autocomplete results list) from selection (choosing the lesson and navigating to it). To avoid people accidentally navigating to a lesson while flicking through the results), I added a confirmation button, "Start". This consistently confuses me when I click an autocomplete lesson result and expect it to navigate straight to the lesson and nothing happens.

**Comment by paulfioravanti** [comment]
Personally, I've never used it. If it decreases the code maintenance burden, then I would be fine with removing it until a real need for it arises.

**Comment by didoesdigital** [comment]
I've added a lessons search/filter to the lessons index page, so for anyone who was using search (including me for testing), there's another option now, so we can remove search from the top nav without reservation.

I had another look at recent search analytics and the only item of note was folks searching for "custom lesson" and similar so I added a special case for that search term on the lessons index to show a link to the custom lesson page.

**Comment by didoesdigital** [comment]
Link to relevant PR: https://github.com/didoesdigital/typey-type/pull/79
