### ISSUE TITLE
Unable to determine word boundaries when practicing multiword briefs

### ISSUE THREAD

**Issue by mayka-mack** [didoesdigital/typey-type#31]
When drilling multi-word entries, the word list does not reliably help determine what is coming next. For example, in the screenshot below it is hard to know if the next entries will be “is it” then “is the”, or “is” then “it is the”.

Further fading out the words after the next phase, showing an underline for the upcoming phrase, or having a separator character between entries might help with this issue.

![image](https://user-images.githubusercontent.com/38409553/84769611-234d7e80-afa4-11ea-9595-c9b5404b1d7f.png)

**Comment by didoesdigital** [comment]
Typey Type will now show a dotted underline for upcoming multi-word phrases that contain spaces (and continue to show no underline for any other upcoming material):

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2476974/152634966-fdd62cd7-9e18-4548-b92d-4fcc17f532b6.png">

Thanks for creating this issue, sharing the problem, and suggesting possible options for solving it! Hope this helps.
