### ISSUE TITLE
Markdown lesson dictionary hint addition

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/typey-type#39]
On the [Markdown lesson](https://didoesdigital.com/typey-type/lessons/collections/tech/markdown/), similar to the [Jeremy GG: phrasing briefs lesson](https://didoesdigital.com/typey-type/lessons/drills/jeremygg-phrasing-briefs/), it might be worth putting some kind of hint there that in order to complete the lesson, [this custom markdown dictionary](https://github.com/didoesdigital/steno-dictionaries/blob/master/dictionaries/markdown.json) should be used.

**Comment by didoesdigital** [comment]
I've added `Hint: use the relevant tech dictionary` to all the tech collection lessons, and similar for the HR lesson, UX lesson, and The Man from Snowy River in https://github.com/didoesdigital/typey-type-data/commit/758307e98b4e5a71be08cc103100a24a7b7aca33

I'm planning on re-working lesson index metadata to store hints in a different place. When that happens, I'll tailor the tech collection hints to link to their specific dictionaries.
