### ISSUE TITLE
Existing progress data is no longer valid.

### ISSUE THREAD

**Issue by Autoencoderg** [didoesdigital/typey-type#53]
As of 41d26a27bcaa278340d5f83d9a64e88e489b958c, the style of existing progress data is now invalid and all new words are regarded as new (at least for those using "ignore spacing") as there is now a combination of words with spaces and words without in the progress data. These are regarded as completely separate words (including punctuation and capitalization).

Whereas previously, a space was added to the front of words discovered by users of "ignore spacing", the space is no longer there for words. The program does not register that "was" and " was" are the same word.

Is it necessary to store space, punctuation, and capitalization in the progress data?

**Comment by didoesdigital** [comment]
Oh no! I thought I had considered all the implications but clearly I missed one. Let's think this through...

- Now when the steno engine is set to space before and Typey Type is set to ignore spaces, the material will ask for "was", you'll likely write " was", get that recorded as "was" and see "was" in revision lessons, where you'll again type " was" (or "was" or "was ") and continue happily. You could write any spacing combination and get "was" recorded so the count for that word would be high, say 35 as a memorised word.
- Previously if material asked for "was", and you wrote " was", it was recorded as " was", shown as " was" in revision lessons, and then if you wrote " was" (or "was" or "was ") that was also happily accepted. If you consistently wrote " was", the count for that word would be high, say 35 times, but if you wrote a mix of spacing you would get a mix of counts, e.g. " was": 25, "was": 5, "  was": 5.
- So, for the migration from old behaviour to new, if you were consistent with your spacing, you would now be asked for "was" like it was a new word you hadn't seen before. If you were inconsistent with your spacing, you would see each spacing variation as a word you had seen but not memorised.

Overall I think the new behaviour is going to be better for new people using this setting, but a pain for existing people during the migration.

I've heard a mix of experiences from people where some consider " was" and "was " the same word in terms of learning the brief and vocabulary but for others they are different words, especially when switching spacing settings on their steno engine and wanting to start again from scratch.

Option A is to ignore spaces and maybe punctuation and capitalisation when recording progress data. The main drawback is that we would lose the ability to practice any of those differently. If "Boolean" is significantly different to "boolean" to you, you cannot practice writing each correctly in different scenarios. Likewise for punctuation and spacing. Spacing in particular matters in prefix/suffix lessons and programming lessons.

Option B is to record them separately but combine them together in different places like for showing the stats on the progress page. Here is a related issue but for punctuation: https://github.com/didoesdigital/typey-type/issues/11

Option C could be to offer a feature to update spacing in the progress met words on demand, which would process the json and move spaces around or trim them as needed. Maybe switching spacing in Typey Type could do that automatically. It could be tricky tampering with people's data though and have other unexpected consequences. This approach might better support the mix of people that do and don't consider changed spacing the same word, as well as the short term migration issue.

What are your thoughts?

**Comment by didoesdigital** [comment]
Going with Option C), there is now a button on the [Progress page](https://didoesdigital.com/typey-type/progress) to reformat the progress file on demand:

<img width="1061" alt="typey-type-download-reformatted-progress-file" src="https://user-images.githubusercontent.com/2476974/153692157-bee77fc9-916f-400a-a3dd-50dda3fa029e.png">

**Comment by didoesdigital** [comment]
Thanks for raising the issue @Autoencoderg . If you have more feedback on this please let me know.
