### ISSUE TITLE
Settings "Upcoming words" should be radio box setting

### ISSUE THREAD

**Issue by YannCebron** [didoesdigital/typey-type#87]
there's only two variants, which makes combo-box superfluous

**Comment by didoesdigital** [comment]
Thanks for that input! Good point. Using a radio button would make the options more visible and it would be more efficient to immediately select the desired value compared to opening the "select" combo-box, selecting a value, and closing it again. On the other hand, I've found it useful to keep the controls in each section of the settings as similar as possible to help people find and understand them quickly.

On the balance, I'm not sure which would have been better but I've recently [added an additional option for "hidden" upcoming words](https://github.com/didoesdigital/typey-type/pull/88) thanks to recent feedback. I think that just makes the difference to keep it as a select combo-box.

Thanks again! If there are other considerations, feel free to re-open the issue.
