### ISSUE TITLE
Provide textual description for symbol/punctuation items

### ISSUE THREAD

**Issue by YannCebron** [didoesdigital/typey-type#96]
Sometimes it's a bit hard to distinguish the symbol to type.

e.g. `“` vs.  `”` and `‘` vs.  `’`

Ideally, TT would add descriptions to all symbols by using some builtin map symbol->description text and show it automatically. This would also help using custom lessons to use non-default dicts (e.g. Emily Symbol System).

**Comment by didoesdigital** [comment]
Thanks for sharing this @YannCebron ! 

Are there particular lessons where punctuation is hard to distinguish? E.g. the punctuation lesson specifically or coding lessons or story lessons with dialogue or…?

Where might textual descriptions appear?

I didn’t quite follow what you meant about “help using custom lessons to use non-default dicts (e.g. Emily Symbol System)”, can you share some more detail there?

**Comment by YannCebron** [comment]
Technically this should appear everywhere punctuation appears, probably via setting to turn it on/off.

Whenever a "punctuation word" appears, its textual description could be shown underneath it to clarify the current symbol.
<img width="330" alt="s" src="https://user-images.githubusercontent.com/570887/197387070-c4f1f77c-8455-4519-916a-bbe257f084ff.png">

w/r to custom lessons, e.g. https://github.com/EPLHREU/emily-symbols offers way more punctuation symbols than the ones commonly appearing in TT lessons and regular texts, and the variations are thus more subtle making this feature even more needed.

**Comment by didoesdigital** [comment]
Ah! That all makes sense. I appreciate the extra detail and the visual.

This might work well as a setting called “Punctuation descriptions” next to “Simple typography”, so that people can turn it off if it’s too much visual clutter for them that they find it distracting, but it could default to on so it’s easy to discover.

It could possibly show a description for any material that is made only of punctuation i.e. `;` and`/*` but not `”example.”` where sentence context could help distinguish punctuation characters. It might be useful to have a limit and only show it on something like 3 character items so it doesn’t show a dozen words on `============` in the markdown lesson.

For the multi-line layout I think it makes sense to show the description in the same spot. It could possibly be in a `p` (paragraph) linked to the text input by `aria-describedby` to indicate it is describing the form field.

**Comment by didoesdigital** [comment]
It might also be useful with the speak content with words setting too!

**Comment by didoesdigital** [comment]
@YannCebron I've just published a version that starts with showing descriptions for quotation marks and back ticks, only for single-character items. Let me know what you think!

<img width="204" alt="image" src="https://user-images.githubusercontent.com/2476974/202844103-f89332aa-7ba4-4d49-99e8-c46ca5165785.png">
<img width="356" alt="image" src="https://user-images.githubusercontent.com/2476974/202844129-0e6cf6e8-0787-4c89-824a-e91a86b39739.png">

**Comment by YannCebron** [comment]
Awesome, thanks! But the checkbox doesn't work for me on FF 107, macOS - can't check it.

**Comment by didoesdigital** [comment]
Whoops, I made a couple mistakes. Just published a fix, try it now? (You may need to hard refresh the browser.)

**Comment by YannCebron** [comment]
The checkbox works but has no effect, tried also in private browsing mode.

**Comment by didoesdigital** [comment]
Hmm, what do you see on this [lesson with simple typography turned off, punctuation descriptions turned on, and material with a back tick](https://didoesdigital.com/typey-type/lessons/fundamentals/punctuation/?startFromWord=26&newWords=1&seenWords=1&retainedWords=1&simpleTypography=0&punctuationDescriptions=1)?

**Comment by YannCebron** [comment]
There it works. It stops working when enabling "Simple typography" ??

**Comment by didoesdigital** [comment]
Simple typography turns back ticks into plain apostrophes, and so far punctuation descriptions are only shown for back ticks and curly quotation marks, to try it out on the weirdest, hardest-to-spot punctuation.

Do you think it makes sense to A) show the description for both back ticks and apostrophes when punctuation descriptions is on and simple typography is off or B) show the description only for the less common character?

**Comment by YannCebron** [comment]
OK got it, the tooltip even says "hard to distinguish". I'd prefer to show it for _any_ punctuation symbols, even if user is not confused, it still helps learning and memorising the correct terms for every symbol (especially for non-native users).

**Comment by didoesdigital** [comment]
That makes sense. Hmm, so does that mean for the punctuation lesson, for example, you'd expect C) *every* punctuation symbol to show a description?

**Comment by YannCebron** [comment]
yes, every single one :)

**Comment by didoesdigital** [comment]
I'll make some changes ⏳

**Comment by didoesdigital** [comment]
Ok, descriptions for everyone!
<img width="190" alt="image" src="https://user-images.githubusercontent.com/2476974/202847692-736d9f8e-6d45-47e1-817f-527ffac25016.png">

Here's the full list for now: https://github.com/didoesdigital/typey-type/blob/master/src/utils/describePunctuation.ts

It could do with some more currency symbols but I ran out of energy. If you have more you'd like to add, feel free to paste them here following the format in that file and I'll get them added!

**Comment by didoesdigital** [comment]
Oh and here's a lesson to try them out: https://docs.google.com/spreadsheets/d/1AlO2SSUwuv3yrz7RI9ix_z1Efbiu_j50c_ibGYwdsgc/edit#gid=2028995866

**Comment by YannCebron** [comment]
That looks quite complete! Thanks :)

**Comment by didoesdigital** [comment]
Let me know how it goes!
